### ISSUE TITLE
Cross compilation?

### ISSUE THREAD

**Issue by eboatwright** [petelomax/Phix#10]
I was wondering if there is any cross compilation support. For example, from Ubuntu Linux to Windows?

**Comment by petelomax** [comment]
Absolutely! In fact the Linux executables are always built here on Windows, by phixzip.exw, see p32.exu and p64.exu.
The reverse, as asked for, would simply be be "format PE32" and/or "format PE64", plus of course a -c in the command line.

**Comment by eboatwright** [comment]
Ayy thanks! :D
