### ISSUE TITLE
Where I can ask Phix questions?

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [petelomax/Phix#12]
Hello there, 
I have a couple of questions about Phix.
First: Can I run it on Mac M1 architecture?
Second: How small it can be? Memory footprint. 
Third: Is there any Phix IRC channel or something?

**Comment by petelomax** [comment]
Sadly Phix is x86-based and has no support for ARM. It would be a long tough project (2 or 3 years probably) and I simply don't have the time/funding or hardware (though an emulated Raspberry PI on Windows is a vague possibility) for that, sorry.
32-bit executables are typically 300KB..3MB, with 64-bit going up to 4.5MB.
You can ask questions on https://openeuphoria.org/forum/index.wc about Phix and it's sibling Euphoria - the latter /may/ be a better fit for ARM architectures, as things stand. Should you want, I'll discuss one other possibility there, that of Phix getting a transpiler to C (it already has one to JavaScript, and that should be a much easier route than ARM direct, but it would lose out a bit as compiler only and no interpreter).

**Comment by petelomax** [comment]
Incidentally, I've just heard of "Rosetta 2", via a new language called Blade, which claims that allows x86 binaries to run on M1, so that might be an option?

**Comment by petelomax** [comment]
UPDATE: Obviously somewhat peeved by my own utter ineffectiveness regarding ARM, I googled upon https://www.dynamsoft.com/codepool/raspberry-pi-emulator-qemu-windows.html - 99% of which I'd already done (via other pages) around 4 years ago, but missed one vital ingredient: pscp, which I'd never head of before today. While there is still a huge mountain to scale, I am at least and at last in a position to twiddle now and then. Should you by any chance know of a similar way to emulate M1 on windows I'm all ears, but anything actually usable is sure to be a long wait. Anyway, genuinely, a million thanks. Sometimes simply asking the right question at the right time can be enormously helpful.

**Comment by the-man-with-a-golden-mind** [comment]
It would be amazing if you would make it portable. It is so light that it
should be everywhere :)

czw., 23 cze 2022, 03:24 użytkownik Pete Lomax ***@***.***>
napisał:
