### ISSUE TITLE
Ubuntu upgrade: p executable doesn't work anymore

### ISSUE THREAD

**Issue by loo66** [petelomax/Phix#13]
Hi,

the p executable 64bit V1.0.1 worked fine on Ubuntu 20.04.x. Yesterday I upgraded to Ubuntu 22.04 - the p executable crashes with a segmentation violation ...

Greetings
Otto

**Comment by bluebat** [comment]
Same problem on Fedora 36.

**Comment by petelomax** [comment]
Sorry, could have sworn blind I'd posted a link here to https://openeuphoria.org/forum/136973.wc#136973

Probably something on https://kernelnewbies.org/LinuxChanges - one of the tips on that site is to run something called dmesg...

**Comment by loo66** [comment]
tried dmesg ... gives this:

```
[ 107.121214] p[4370]: segfault at 0 ip 00007f3d725b8350 sp 00007ffea111fba0 error 4 in ld-linux-x86-64.so.2[7f3d72598000+2a000]
[ 107.121230] Code: ff ff 00 45 31 db 48 8d 15 c9 ac 00 00 4c 8d 05 46 8f 01 00 4c 8d 2d 1f 8f 01 00 49 89 c2 48 8d 58 ff 48 89 f8 49 f7 da 66 90 <8b> 08 83 f9 07 77 19 85 c9 74 45 83 f9 07 77 40 48 63 0c 8a 48 01
```

but I don't know how to continue from this (not a *nix system guy) ...

**Comment by loo66** [comment]
tried to step back to 20.04.x ... installed 20.04.5 ... same issue ! :-(
can't remember the exact 20.04 version I had before ...

**Comment by petelomax** [comment]
Can everyone run quickly run "ldd --version" (please) to check whether as I suspect there is indeed a correlation between glibc 2.36 and Phix segfaulting?

**Comment by loo66** [comment]
I have now 2.31 with 20.04.5

**Comment by bluebat** [comment]
2.34 with Fedora 35
2.35 with Fedora 36

**Comment by petelomax** [comment]
Update:  on a fresh mint 21 cinnamon install, ./p64 segfaults, but /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 ./p64 works...???

**Comment by rzuckerm** [comment]
p executable doesn't seem to work in Ubuntu 20.04 either. I'm trying to build a phix docker image, and it crashes when I run `p -test` with a segmentation fault. However, if I do the `/usr/lib/...` trick, it works fine 🤷

**Comment by rzuckerm** [comment]
However, `/usr/lib/... p -c` segfaults

**Comment by petelomax** [comment]
You might be able to do p -c -norun, and then the /usr/lib/... trick....
I need to go and chase this up again, don't I?

**Comment by rzuckerm** [comment]
`p -c -norun` seemed to work. Then I was able to run the executable using the `/usr/lib` trick.

**Comment by petelomax** [comment]
My lord, forsooth behold a genius, he hath taken nary six monthen for to patchen just twelf byten!
It be told the gnomes of elfland hath strictethened theirly p_align necessitibilitationes, hallelulah!

Anyway, crisis over, I hope.

The manual patches I made to the elf binaries have yet to be realised in the hll source code.
I have uploaded patched 1.0.1 binaries, but interpretation-only, with any compilation still
expected to segfault. Will get to work on building/testing/shipping 1.0.2 straight away.

**Comment by loo66** [comment]
works fine ... thx for your efforts

cheers
Otto

**Comment by rzuckerm** [comment]
@petelomax I see that 1.0.2 just came out. Do compiled executable still have to be run through /usr/lib/...?

**Comment by rzuckerm** [comment]
@petelomax It looks like this problem may be fixed. I'm able to run `p` and the compiled executables without having to use the /usr/lib/... trick. Thanks!

**Comment by petelomax** [comment]
Been offline for 8 days (both O2 & BT down, lightening strike on local mast/doobrie, methinks). 1.0.2 has been out a fortnight and seems fine, so closing this issue
