### ISSUE TITLE
A little mistake on "Readme" section

### ISSUE THREAD

**Issue by McGyverItaly** [petelomax/Phix#14]
<<...For example if s="food" then s[2..3]="e" makes s "fed", and then s[2..1]="east" makes s "feasted".>> is wrong.

<<...For example if s="food" then s[2..3]="e" makes s "fed", and then s[2..**2**]="east" makes s "feasted".>> is correct.

**Comment by McGyverItaly** [comment]
If s="fed", s[2..2]="east" makes s "feastd". If the second slicing index is **lower** than the first, this allow "east" to be inserted **between the first and the second** charachter of s. Very interesting indeed...

**Comment by petelomax** [comment]
I think you've got this but s[2..2]="east" would replace a length 1 substring, giving "feastd", whereas
s[2..1] replaces a length 0 substring, giving "feasted".

The second slicing index can be equal to or greater but only be 1 less than the first, if you tried say 
s[3..1] := "x" then you'd get a "slice length is negative" error.

You have probably used a language with 0-based indices, and I hope you'll find 1-based are much nicer,
without such nonsense as Python's range(10) stopping at 9.
