### ISSUE TITLE
phix 1.0.2 download doesn't seem to be available

### ISSUE THREAD

**Issue by rzuckerm** [petelomax/Phix#15]
The [download instructions for Linux](http://phix.x10.mx/download.php) indicate that phix can be downloaded using `wget` instructions like this:
```
wget http://phix.x10.mx/phix.1.0.2.zip
...
```
However, when I do this, I get a 404 error.

**Comment by petelomax** [comment]
Ah, when I added the warning I accidentally bumped it up to a version number that hasn't shipped yet, should be better now.

**Comment by rzuckerm** [comment]
It doesn't seem to be fixed:
```console
$ wget http://phix.x10.mx/phix.1.0.2.zip
--2023-01-17 07:19:01--  http://phix.x10.mx/phix.1.0.2.zip
Resolving phix.x10.mx (phix.x10.mx)... 198.91.81.15
Connecting to phix.x10.mx (phix.x10.mx)|198.91.81.15|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-01-17 07:19:02 ERROR 404: Not Found.
```

**Comment by petelomax** [comment]
Was that a hiccup? Did you just delete a response on the github issue page?
It was the text on the download page and therefore the url which were wrong, should be[/have been] "1.0.1".
I've also just updated the warning, so I might have uploaded without saving first, or you could have had a cached copy..

     On Tuesday, 17 January 2023, 13:20:34 GMT, rzuckerm ***@***.***> wrote:  
 
 


It doesn't seem to be fixed:
$ wget http://phix.x10.mx/phix.1.0.2.zip--2023-01-17 07:19:01--  http://phix.x10.mx/phix.1.0.2.zipResolving phix.x10.mx (phix.x10.mx)... 198.91.81.15Connecting to phix.x10.mx (phix.x10.mx)|198.91.81.15|:80... connected.HTTP request sent, awaiting response... 404 Not Found2023-01-17 07:19:02 ERROR 404: Not Found.

**Comment by rzuckerm** [comment]
Sorry, I deleted the comment since I misunderstood your reply. I was expecting the 1.0.2 version to be available. When I went to your site, I saw the you had corrected the links and instructions. Therefore, my comment was irrelevant.
