### ISSUE TITLE
Strange Error when attempting to use 8.2

### ISSUE THREAD

**Issue by LamentConfiguration** [petelomax/Phix#2]
I downloaded 8.1 and installed it per the instructions on the website.

I then downloaded a zip of the git repo, unzipped it, named it Phix (8.1 Phix to Phix_old) and copied pw.exe from the old to the new (8.2) file, and used the installation instructions to recompile the compiler using the 8.2 source.

p -test ran fine.

when i go to do pw edita.exw in the proper folder, it fails with the following:
![image](https://user-images.githubusercontent.com/15186074/99828474-985b4c00-2b20-11eb-8984-1d2d22ba6b6f.png)

I am also including the text from ex.err as per the screenshot.
[ex.txt](https://github.com/petelomax/Phix/files/5575041/ex.txt)

This also occurred when I tried to run manip.exw from the pgui launched with pw. Except it was with regards to int and not bool.

If i messed up in some way with my attempt to "update" to 8.2 I apologize for making this mess of a post.

**Comment by petelomax** [comment]
Ah, a release of 0.8.2 is way overdue... I'll pull me finger out!
On my internal copy, I simply commented out the whole type bool (3 lines), not that I can quite remember doing that, in case that helps any.

**Comment by LamentConfiguration** [comment]
Looking forward to 0.8.2! Thanks for the prompt reply 👍

**Comment by r-k-o** [comment]
So do I. When is it coming?
I tried to compile from the sources - but it didn't work. It is missing JS in get_interpreter.e

**Comment by petelomax** [comment]
0.8.2 has been uploaded

**Comment by LamentConfiguration** [comment]
Thank you!
