### ISSUE TITLE
t64 test fails with 0.8.2

### ISSUE THREAD

**Issue by loo66** [petelomax/Phix#3]
Testing[59]: /home/thales/phix/test/t64struct.exw
[1;5,2] + 1/2   ->  [1;1,2,7,36600682685931650]

/home/thales/phix/test/t64struct.exw:598
attempt to divide by 0

greetings
Otto

**Comment by petelomax** [comment]
Thanks, irv just beat you to this. Inadequately tested on 64-bit, I've simply changed it (ie t64struct.exw line 596):
--for i=1 to length(dd) do 
for i=iff(machine_bits()=32?1:4) to length(dd) do
